name: CI/CD Deploy Frontend to NKS

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker image (Frontend)
        run: |
          IMAGE_TAG=$(echo "$GITHUB_SHA" | cut -c1-7)
          docker build -t rosco0611/javis-fe:${IMAGE_TAG} -t rosco0611/javis-fe:latest "$GITHUB_WORKSPACE"
          docker push rosco0611/javis-fe:${IMAGE_TAG}
          docker push rosco0611/javis-fe:latest
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update Kubernetes deployment image tags
        run: |
          sed -i "s|image: rosco0611/javis-fe:.*|image: rosco0611/javis-fe:${IMAGE_TAG}|g" k8s/frontend.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend.yaml
          kubectl rollout restart deployment/javis-fe
          kubectl apply -f k8s/ingress-frontend.yaml
          kubectl rollout status deployment/javis-fe --timeout=180s