# .github/workflows/deploy.yml
name: CI/CD Deploy Frontend to NKS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker image (Backend)
        run: |
          docker build -t rosco0611/javis-fe:latest "$GITHUB_WORKSPACE"
          docker push rosco0611/javis-fe:latest

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f "$GITHUB_WORKSPACE/k8s/clusterissuer.yaml"
          kubectl apply -f "$GITHUB_WORKSPACE/k8s/backend.yaml"
          kubectl apply -f "$GITHUB_WORKSPACE/k8s/frontend.yaml"
          kubectl apply -f "$GITHUB_WORKSPACE/k8s/ingress-frontend.yaml"
          kubectl rollout status deployment/fastapi-backend --timeout=120s || exit 1